import Head from 'next/head'
import Image from 'next/image'

import { Box, Code, Flex, Heading, SimpleGrid, Text, Center, Container, VStack } from '@chakra-ui/react'

import Details from '../src/components/details'
import Cart from '../src/components/cart'

export default function Home() {
	return (
		<div>
			<Head>
				<title>Demo Chakra-UI </title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<Flex h={{ base: 'auto', md: '100vh' }} py={[0, 10, 20]} direction={{ base: 'column-reverse', md: 'row' }}>
				Home
				{/* <Details />
				<Cart /> */}
			</Flex>
		</div>
	)
}
