import Head from 'next/head'
import Image from 'next/image'

import OvertimeForm from './overtimeForm'

import { Flex, Heading, useDisclosure, Button } from '@chakra-ui/react'

const testFunc = () => console.log('test func')

export default function Home() {
	return (
		<>
			<Head>
				<title>Demo Chakra-UI </title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<Flex h={{ base: 'auto', md: 'full' }} py={[0, 10, 20]} direction={{ base: 'column-reverse', md: 'row' }}>
				HOME
			</Flex>
		</>
	)
}
